FROM node:12-alpine as builder
COPY yarn.lock /yarn.lock
COPY package.json /package.json
ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
RUN yarn install

FROM node:12-alpine as server
WORKDIR /app
COPY --from=builder /node_modules /app/node_modules
COPY . /app
EXPOSE 3000
EXPOSE 35729
ENTRYPOINT ["/bin/sh", "/app/run.sh"]
CMD ["start"]
